spring.application.name=PixayAPI
server.port=8081

# --- CONFIGURACIÓN DE BASE DE DATOS ---
# Usamos testdb como nombre de la base de datos en memoria
spring.datasource.url=jdbc:h2:file:./data/pixay-db;AUTO_SERVER=TRUE
  #DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

# | | | | | | | | | | | | | | | | | |
# v v v v v v v v v v v v v v v v v v
#UNA VEZ CREADO EL ARCHIVO DB COMENTAR
#spring.sql.init.mode=always
# ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^
# | | | | | | | | | | | | |

# --- HIBERNATE / JPA ---
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true

spring.sql.init.encoding=UTF-8
# --- CONSOLA H2 ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- SEGURIDAD Y JWT ---
#TODO CRIS: Pelear para que no se pueda leer el JWT
JWT_SECRET=Z3VlcmNhLWxhLWJpZW4tbGEtc2VndXJpZGFkLWRlLXBpeGF5LTIwMjYtZGF3LXRmZw==
JWT_EXPIRATION=24
# Ya no ponemos el ${} aquí para que no de error circular
# Spring leerá los valores directamente de las variables de entorno de IntelliJ
#jwt.secret.status=externalized

# Evita que Spring Security genere una contraseña aleatoria en el log
spring.main.allow-bean-definition-overriding=true

# Tamaño máximo del archivo
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB