spring.application.name=PixayMVC
server.port=8080
spring.thymeleaf.cache=false

# H2 en memoria para usuarios/roles de la app MVC
#para poder tener el h2 en memoria:
spring.datasource.url=jdbc:h2:mem:pixay_mvc_db;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Credenciales para conectar con la API
api.base-url=http://localhost:8081/api/
api.auth-url=http://localhost:8081/auth/
api.auth-username=admin
api.credential=admin
api.auth-password=admin123

# Tamaño máximo del archivo
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


JWT_SECRET=Z3VlcmNhLWxhLWJpZW4tbGEtc2VndXJpZGFkLWRlLXBpeGF5LTIwMjYtZGF3LXRmZw==
JWT_EXPIRATION=86400000
spring.main.allow-bean-definition-overriding=true